name: OIDC → AWS test

on:
  workflow_dispatch:

jobs:
  sts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::457664479040:role/gha-oidc-demo
          aws-region: us-east-1

      - name: Show caller identity
        run: aws sts get-caller-identity --output json


